In [2]:
import numpy as np


In [3]:
from time import process_time

In [ ]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5

end_time = process_time()

print(end_time - start_time)

numPy Arrays


In [12]:
np_array = np.array([1,2,3,4,5])

print(np_array)
print(type(np_array))

list_1 = [1,2,3,4,5,6]
print(list_1)
print(type(list_1))

con = np.array(list_1)
print(type(con))

[1 2 3 4 5]
<class 'numpy.ndarray'>
[1, 2, 3, 4, 5, 6]
<class 'list'>
<class 'numpy.ndarray'>


1D ARRAY


In [ ]:
a = np.array([1,2,3,4])
print(a.shape)

a_1 = np.ones((2,3,4),dtype = int)
print(a_1)

(4,)
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]



2D ARRAY

In [ ]:
b = np.array(
    [
    (1,2,3,4),
    (5,6,7,8)
    ])
print(b)
print(b.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


Initial place holders in numpy


In [6]:
# numpy of zeroes

x = np.zeros((4,5),dtype=int)
print(x)
print(type(x))

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
<class 'numpy.ndarray'>


In [4]:
# numpy of ones

y = np.ones((4,5) , dtype=int)
print(y)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [ ]:
# numpy of AnyValue
z = np.full((2,5),5)
print(z)

z_2 = np.full((6,7),8)
print(z_2)

[[5 5 5 5 5]
 [5 5 5 5 5]]
[[8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8]]


In [ ]:
#Identity matrix

iden = np.eye( 7 , dtype=int)
print(iden)

iden_1 = np.eye(4,2,dtype=int)
print(iden_1)

[[1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 0 1 0 0]
 [0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1]]
[[1 0]
 [0 1]
 [0 0]
 [0 0]]


In [ ]:
# numpy array with random values , values lies between 0 - 1

a = np.random.random((4,5))
print(a)

[[0.40521174 0.75156992 0.20628671 0.91314808 0.3114891 ]
 [0.72362213 0.97956977 0.63479734 0.56500797 0.48129813]
 [0.84987753 0.87408222 0.43368343 0.39615348 0.84404786]
 [0.72592911 0.58843302 0.4591219  0.00658338 0.43694256]]


In [10]:
# numpy array with random value but with settable range

b = np.random.randint(10,100,(4,5))
print(b)

[[79 55 81 64 12]
 [33 35 30 25 86]
 [40 36 86 69 12]
 [92 96 17 38 13]]


In [11]:
#array of evenly spaced --> number of values requires

d = np.linspace(5,10,8,dtype=int)
print(d)

[ 5  5  6  7  7  8  9 10]


Analyzing the arrays

In [15]:
c = np.random.randint(10,70,(4,4))
print(c)

[[55 39 14 39]
 [27 19 14 16]
 [13 54 60 64]
 [40 22 26 22]]


In [17]:
#array dimension

print(c.shape)

(4, 4)


In [19]:
#number of dimension

print(c.ndim)

2


In [20]:
#number of elements in a array

print(c.size)

16


Mathematical operations on numpy array

In [21]:
a = np.random.randint(0,10,(4,4))
b = np.random.randint(10,20,(4,4))

In [23]:
print(a)
print(b)

[[8 6 9 1]
 [5 7 2 1]
 [7 5 9 6]
 [8 5 3 5]]
[[11 17 17 18]
 [16 19 13 14]
 [19 10 17 11]
 [12 13 15 18]]


In [24]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[19 23 26 19]
 [21 26 15 15]
 [26 15 26 17]
 [20 18 18 23]]
[[ -3 -11  -8 -17]
 [-11 -12 -11 -13]
 [-12  -5  -8  -5]
 [ -4  -8 -12 -13]]
[[ 88 102 153  18]
 [ 80 133  26  14]
 [133  50 153  66]
 [ 96  65  45  90]]
[[0.72727273 0.35294118 0.52941176 0.05555556]
 [0.3125     0.36842105 0.15384615 0.07142857]
 [0.36842105 0.5        0.52941176 0.54545455]
 [0.66666667 0.38461538 0.2        0.27777778]]


Array manipulation


In [26]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[1 4 7]
 [7 2 3]]
(2, 3)


In [28]:
#tranpose of matrix

print(np.transpose(array))
print(array.T)

[[1 7]
 [4 2]
 [7 3]]
[[1 7]
 [4 2]
 [7 3]]


Reshape

In [32]:
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[5 5 0]
 [1 6 3]]
(2, 3)


In [36]:
#Reshaping

print(a.reshape(3,2))
print(a.reshape(6,1))

[[5 5]
 [0 1]
 [6 3]]
[[5]
 [5]
 [0]
 [1]
 [6]
 [3]]
